CREATE TABLE users ( 
	id 			SERIAL 		PRIMARY KEY,
	first_name 	VARCHAR(50) NOT NULL,
	last_name 	VARCHAR(50) NOT NULL,
	email 		VARCHAR(50) UNIQUE NOT NULL,
	username 	VARCHAR(20) UNIQUE NOT NULL,
	password 	VARCHAR 	NOT NULL,
	is_admin 	BOOLEAN 	NOT NULL DEFAULT false,
	status 		INTEGER 	NOT NULL DEFAULT 1
);

CREATE TABLE quinielas ( 
	id 			SERIAL 		PRIMARY KEY,
	created_at 	DATE 		NOT NULL DEFAULT CURRENT_DATE,
	ended_at 	DATE 		DEFAULT NULL,
	user_id 	INTEGER 	NOT NULL REFERENCES users ( id ) ON DELETE CASCADE,
	status 		INTEGER 	DEFAULT 0 NOT NULL
 );

